# Generated by Django 5.0.2 on 2024-04-19 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=15)),
                ('tasa_comision', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nit', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('contador', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('contador_ref', models.CharField(max_length=20)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operacion.asesor')),
                ('nit_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operacion.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operacion.producto')),
            ],
        ),
    ]
