# Generated by Django 5.0.2 on 2024-04-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='contador_ref',
            new_name='contador',
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
